### ISSUE TITLE
Implement a /register POST endpoint

### ISSUE THREAD

**Issue by pa3ng** [ianbeh96/ProjectChallenge.io-api#6]
## TODO

- [ ] **Task 1**: Update `users` table in database to add `firstname` and `lastname` fields, both `NOT NULL`
- [ ] **Task 2**: Also add a `user_id` field to the `users` table. This field is `NOT NULL`
- [ ] **Task 3**: Implement POST `/users` route

**Note for Task 2**

For the `user_id`, rather than making up our own IDs, we can import and use Python's [`uuid` package](https://docs.python.org/3/library/uuid.html) to generate a UUID as the `user_id` of the task. (We'll do this as well for the `challenge_id` of challenges and `task_id` of tasks.)

**Note for Task 3**

The endpoint function should return the `201` **status code** (standard for successful POST)

Example request

```sh
curl \
  -X POST \
  -H "Accept: application/json" \
  http://localhost:5000/users \
  -d '{"firstname":" raph", "lastname": "santo", "password": "password", "email": "santo141@umn.edu"}'
```

**Comment by pa3ng** [comment]
UPDATE

change `POST /users` endpoint to `POST /register`
